all:		 Peer.class SuperNode.class App.class

Peer.class:	Peer.java
			@javac Peer.java

SuperNode.class:		SuperNode.java
			@javac SuperNode.java

App.class:	App.java
			@javac App.java

clean:
			@rm -rf *.class *~
